version: '3.9'

services:
  backend:
    build: ./backend
    restart: always
    environment:
      - origins=['http://frontend:3000']

  frontend:
    build: ./frontend
    restart: always
    ports:
      - '3000:3000'
    environment:
      - API_URL=http://backend:8000
 